import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router';
import { CalendarDays, Clock3, Dumbbell, History, Home, IdCard, LogOut, Menu, RefreshCw, Settings, ShieldCheck, UserRound, WifiOff } from 'lucide-react';
import { memberApi, type MemberUser, type Overview } from './api';

type Loadable<T>={data?:T;loading:boolean;error?:string};
function useLoad<T>(loader:()=>Promise<T>){const [version,setVersion]=useState(0);const [state,setState]=useState<Loadable<T>>({loading:true});useEffect(()=>{let active=true;setState({loading:true});loader().then(data=>active&&setState({data,loading:false})).catch((e:Error)=>active&&setState({loading:false,error:e.message}));return()=>{active=false}},[version]);return{...state,reload:()=>setVersion(v=>v+1)}}
const nav=[['/home','Home',Home],['/membership','Membership',IdCard],['/attendance','Attendance',History],['/coaches','Coaches',Dumbbell],['/account','Account',Settings]] as const;

function State({loading,error,reload,empty}:{loading:boolean;error?:string;reload:()=>void;empty:string}){if(loading)return <div className="state"><RefreshCw className="spin"/><strong>Loading your records</strong></div>;if(error)return <div className="state error"><WifiOff/><strong>Could not reach the server</strong><span>{error}</span><button onClick={reload}>Try again</button></div>;return <div className="state"><Clock3/><strong>{empty}</strong><span>No sample information is displayed.</span></div>}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
function Header({title,subtitle,icon}:{title:string;subtitle:string;icon:ReactNode}){return <header className="page-head"><span>{icon}</span><div><h1>{title}</h1><p>{subtitle}</p></div></header>}

function Shell({user,onLogout}:{user:MemberUser;onLogout:()=>Promise<void>}){const [open,setOpen]=useState(false);const location=useLocation();return <div className="shell"><header className="top"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><Link to="/home"><img src="/logo.png" alt="X-TRIM FIT GYM"/></Link><div className="person"><span>{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><small>{user.memberNumber}</small></div></div></header>{open&&<button className="scrim" onClick={()=>setOpen(false)}/>}<aside className={open?'open':''}><div className="member-mini"><span>{user.firstName[0]}{user.lastName[0]}</span><strong>{user.firstName} {user.lastName}</strong><small>Member · {user.memberNumber}</small></div><nav>{nav.map(([path,label,Icon])=><Link key={path} to={path} onClick={()=>setOpen(false)} className={location.pathname===path?'active':''}><Icon/><span>{label}</span></Link>)}</nav><button className="logout" onClick={onLogout}><LogOut/>Log out</button></aside><main><Routes><Route path="/home" element={<HomePage user={user}/>}/><Route path="/membership" element={<MembershipPage/>}/><Route path="/attendance" element={<AttendancePage/>}/><Route path="/coaches" element={<CoachesPage/>}/><Route path="/account" element={<AccountPage user={user}/>}/><Route path="*" element={<Navigate to="/home" replace/>}/></Routes></main></div>}

function HomePage({user}:{user:MemberUser}){const result=useLoad(memberApi.overview);const d=result.data;return <><Header title={`Welcome, ${user.firstName}`} subtitle="Your membership, visits and gym information in one place." icon={<Home/>}/>{d?<><Card className="member-hero"><div><span className="eyebrow">MEMBERSHIP STATUS</span><h2>{d.membership?.plan??'No active membership'}</h2><p>{d.membership?`Valid until ${new Date(d.membership.expiresAt).toLocaleDateString()}`:'Visit reception to activate a membership.'}</p><span className={`pill ${d.membership?.status==='ACTIVE'?'ok':''}`}>{d.membership?.status??'INACTIVE'}</span></div><IdCard/></Card><div className="summary"><Card><History/><span>Total visits</span><strong>{d.attendanceSummary.totalVisits}</strong></Card><Card><CalendarDays/><span>This month</span><strong>{d.attendanceSummary.visitsThisMonth}</strong></Card><Card><Clock3/><span>Gym today</span><strong>{d.gym.statusLabel}</strong><small>{d.gym.hoursToday}</small></Card></div>{d.announcements.length>0&&<Card><h3>Announcements</h3>{d.announcements.map(a=><article className="announcement" key={a.id}><strong>{a.title}</strong><p>{a.message}</p></article>)}</Card>}</>:<Card><State {...result} reload={result.reload} empty="Your account has no records yet"/></Card>}</>}
function MembershipPage(){const result=useLoad(memberApi.overview);const d=result.data;return <><Header title="My Membership" subtitle="Current plan, validity and NFC card status." icon={<IdCard/>}/>{d?<div className="two"><Card><span className="eyebrow">CURRENT PLAN</span><h2>{d.membership?.plan??'No active plan'}</h2>{d.membership?<dl><div><dt>Status</dt><dd>{d.membership.status}</dd></div><div><dt>Started</dt><dd>{new Date(d.membership.startedAt).toLocaleDateString()}</dd></div><div><dt>Expires</dt><dd>{new Date(d.membership.expiresAt).toLocaleDateString()}</dd></div></dl>:<p>Membership applications and payments are completed at reception.</p>}</Card><Card><span className="eyebrow">NFC MEMBERSHIP CARD</span><h2>{d.card?.status??'Not assigned'}</h2><p>Your card opens this portal on a compatible phone. Official attendance is recorded only at the gym reader.</p></Card></div>:<Card><State {...result} reload={result.reload} empty="No membership details available"/></Card>}</>}
function AttendancePage(){const result=useLoad(memberApi.attendance);return <><Header title="My Attendance" subtitle="Your verified check-ins from the gym attendance station." icon={<History/>}/><Card>{result.data?.items.length?<div className="table"><div className="tr th"><span>Date and time</span><span>Station</span><span>Status</span></div>{result.data.items.map(i=><div className="tr" key={i.id}><strong>{new Date(i.recordedAt).toLocaleString()}</strong><span>{i.station}</span><span className="pill ok">{i.status}</span></div>)}</div>:<State {...result} reload={result.reload} empty="No attendance records yet"/>}</Card></>}
function CoachesPage(){const result=useLoad(memberApi.coaches);return <><Header title="Coaches" subtitle="Published specialties and current availability." icon={<Dumbbell/>}/>{result.data?.items.length?<div className="coach-grid">{result.data.items.map(c=><Card key={c.id}><div className="coach-avatar"><UserRound/></div><h3>{c.fullName}</h3><p>{c.specialty}</p><span className="pill">{c.availability}</span></Card>)}</div>:<Card><State {...result} reload={result.reload} empty="No coach availability published"/></Card>}</>}
function AccountPage({user}:{user:MemberUser}){const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [message,setMessage]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setMessage('');try{await memberApi.updatePassword(current,next);setCurrent('');setNext('');setMessage('Password updated.')}catch(err){setMessage(err instanceof Error?err.message:'Update failed')}};return <><Header title="Account Settings" subtitle="Your login security and member identity." icon={<Settings/>}/><div className="two"><Card><h3>Member information</h3><dl><div><dt>Name</dt><dd>{user.firstName} {user.lastName}</dd></div><div><dt>Member number</dt><dd>{user.memberNumber}</dd></div></dl></Card><Card><h3>Change password</h3><form className="form" onSubmit={submit}><label>Current password<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>New password<input type="password" minLength={10} value={next} onChange={e=>setNext(e.target.value)} required/></label>{message&&<div className="message">{message}</div>}<button>Update password</button></form></Card></div></>}

function Login({onLogin,cardToken}:{onLogin:(u:MemberUser)=>void;cardToken?:string}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await memberApi.login(username,password,cardToken))}catch(err){setError(err instanceof Error?err.message:'Sign in failed')}finally{setBusy(false)}};return <main className="login"><section className="visual"><img src="/logo.png"/><div><span className="eyebrow">YOUR X-TRIM MEMBERSHIP</span><h1>Train hard.<br/>Stay on track.</h1><p>Membership, attendance and gym updates—always within reach.</p></div></section><section className="signin"><div><span className="eyebrow">MEMBER PORTAL</span><h2>Welcome back</h2><p>{cardToken?'Card recognized. Sign in to protect your records.':'Use the account provided at reception.'}</p><form className="form" onSubmit={submit}><label>Username or member number<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="form-error">{error}</div>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><small>No account yet? Membership registration and payment are completed at reception.</small></div></section></main>}
function FirstPassword({onDone}:{onDone:()=>void}){const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();if(next!==confirm){setError('New passwords do not match.');return}try{await memberApi.changeTemporaryPassword(current,next);onDone()}catch(err){setError(err instanceof Error?err.message:'Could not update password')}};return <main className="force"><Card><ShieldCheck/><span className="eyebrow">FIRST SIGN-IN</span><h1>Create your private password</h1><p>Your temporary password must be replaced before you can view member records.</p><form className="form" onSubmit={submit}><label>Temporary password<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required/></label><label>New password<input type="password" minLength={10} value={next} onChange={e=>setNext(e.target.value)} required/></label><label>Confirm new password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<div className="form-error">{error}</div>}<button>Save and continue</button></form></Card></main>}
function CardEntry({onToken}:{onToken:(token:string)=>void}){const {token}=useParams();useEffect(()=>{if(token)onToken(token)},[token,onToken]);return <div className="boot">Opening secure member portal…</div>}

export default function App(){const [auth,setAuth]=useState<{loading:boolean;user?:MemberUser}>({loading:true});const [cardToken,setCardToken]=useState<string|undefined>(()=>sessionStorage.getItem('xtrim-card-token')||undefined);const navigate=useNavigate();useEffect(()=>{if(import.meta.env.DEV&&import.meta.env.VITE_DEV_PREVIEW==='true'){setAuth({loading:false,user:{id:'local-preview',memberNumber:'PREVIEW-ONLY',firstName:'Member',lastName:'Preview',mustChangePassword:false}});return}memberApi.me().then(user=>setAuth({loading:false,user})).catch(()=>setAuth({loading:false}))},[]);const acceptToken=useCallback((token:string)=>{sessionStorage.setItem('xtrim-card-token',token);setCardToken(token);navigate('/login',{replace:true})},[navigate]);const logout=useCallback(async()=>{try{await memberApi.logout()}finally{setAuth({loading:false});navigate('/login')}},[navigate]);if(auth.loading)return <div className="boot"><img src="/logo.png"/>Securing member portal…</div>;if(!auth.user)return <Routes><Route path="/c/:token" element={<CardEntry onToken={acceptToken}/>}/><Route path="*" element={<Login cardToken={cardToken} onLogin={user=>{sessionStorage.removeItem('xtrim-card-token');setCardToken(undefined);setAuth({loading:false,user});navigate(user.mustChangePassword?'/first-password':'/home')}}/>}/></Routes>;if(auth.user.mustChangePassword)return <FirstPassword onDone={()=>{setAuth({loading:false,user:{...auth.user!,mustChangePassword:false}});navigate('/home')}}/>;return <Shell user={auth.user} onLogout={logout}/>}
